version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: sqlserver_db
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: password
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sqlserver_network

volumes:
  sqlserver_data:

networks:
  sqlserver_network:
