version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: redis_server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: ["redis-server"]
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
